[package]
name = "adapt"
version = "0.0.1"
authors = ["Stephan Göppentin <dedda102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"
